default:
  provider: Copilot Chat - Chat Completions
  path: https://api.githubcopilot.com/chat/completions
  include_history: TRUE
  max_data_files: 0
  max_data_frames: 0
  include_doc_contents: FALSE
