default:
  provider: Copilot Chat - Chat Completions
  path: https://api.githubcopilot.com/chat/completions
  include_history: TRUE
  max_data_files: 0
  max_data_frames: 0
  include_doc_contents: FALSE
  system_msg: You are a helpful coding assistant
  model_arguments:
    stream: TRUE
chat:
  prompt: |
    {readLines(system.file('prompt/base.txt', package = 'chattr'))}
    For code output, use RMarkdown code chunks
    Avoid all code chunk options
