default:
  prompt: |
    {readLines(system.file('prompt/base.txt', package = 'chattr'))}
  provider: OpenAI - Completions
  path: https://api.openai.com/v1/completions
  label: Davinci 3 (OpenAI)
  model: text-davinci-003
  max_data_files: 0
  max_data_frames: 0
  include_doc_contents: FALSE
  system_msg: You are a helpful coding assistant
  model_arguments:
    temperature: 0.01
    max_tokens: 1000
    stream: TRUE
chat:
  prompt: |
    {readLines(system.file('prompt/base.txt', package = 'chattr'))}
    For code output, use RMarkdown code chunks
    Avoid all code chunk options
console:
  prompt: |
    {readLines(system.file('prompt/base.txt', package = 'chattr'))}
    Prefix ALL explanations with a pound sign
    Keep each line of explanations to no more than 80 characters
    DO NOT use Markdown for the code
script:
  prompt: |
    {readLines(system.file('prompt/base.txt', package = 'chattr'))}
    Prefix ALL explanations with a pound sign
    Keep each line of explanations to no more than 80 characters
    DO NOT use Markdown for the code

