default:
  tidychat:
    notebook:
      prompt: |
        Use tidyverse packages: readr, ggplot2, dplyr, tidyr
        For models, use tidymodels packages: recipes, parsnip, yardstick, workflows, broom
        skimr and janitor can also be used if needed
        Expecting only code, avoid comments unless requested by user
      provider: OpenAI
      model: DaVinci 3
      include_data_files: TRUE
      include_data_frames: TRUE
      include_doc_contents: TRUE
      system_msg: You are a helpful coding assistant
      model_arguments:
        temperature: 0.01
        max_tokens: 1000
    chat:
      prompt: |
        Use tidyverse packages: readr, ggplot2, dplyr, tidyr
        For models, use tidymodels packages: recipes, parsnip, yardstick, workflows, broom
        skimr and janitor can also be used if needed
        Expecting only code, avoid comments unless requested by user
      provider: OpenAI
      model: DaVinci 3
      include_data_files: TRUE
      include_data_frames: TRUE
      include_doc_contents: TRUE
      system_msg: You are a helpful coding assistant
      model_arguments:
        temperature: 0.01
        max_tokens: 1000
