default:
  prompt: |
    Use the R language, the tidyverse, and tidymodels
  provider: LlamaGPT
  model: LlamaGPT
  max_data_files: 0
  max_data_frames: 0
  include_doc_contents: FALSE
  include_history: FALSE
  model_arguments:
    threads: 4
    temp: 0.01
    model: ~/ggml-gpt4all-j-v1.3-groovy.bin
    chat_path: ~/LlamaGPTJ-chat/build/bin/chat
    n_predict: 1000
